### ISSUE TITLE
CC3200 and pinout request...

### ISSUE THREAD

**Issue by vinceyoumans** [fmilburn3/CardReader_RFID_RC522#1]
your doing some interesting stuff...
what is the PIN OUT for your project. Have you tried this with a CC3200?
thanks

**Comment by fmilburn3** [comment]
The pin connections are shown in the example sketch.  Just tried it on the CC3200, and it works...  For some reason it doesn't seem to work on the MSP432 but I haven't had time to try and track the problem down.

**Comment by vinceyoumans** [comment]
Any chance you can be more specific with the pics... I am vey new to cc3200's  actually to these Micros anyway.

**Comment by vinceyoumans** [comment]
I am still having trouble with your PINS for the CC3200.  I am not sure how you are translating the pins on the board.  In addition, The RC522 that I have are not labeled as is your code.
Probably the same, 
they are:

SDA
SCK
MOSI
MISO
IRQ
GND
RST
3.3v

Anychance you can use this daigram to explain what pins your going to please.

![cc3200launchxl_top_silk_rev4p1](https://cloud.githubusercontent.com/assets/47495/11550164/f13eaa88-993a-11e5-9896-11182e0ddf77.png)
